### ISSUE TITLE
self signed certificate

### ISSUE THREAD

**Issue by OKNoah** [matomo-org/matomo-nodejs-tracker#48]
Currently I get the error `self signed certificate`. My matomo uses a self-signed cert and I've had trouble setting up `letsencrypt` on it. Is this the library complaining or Matomo itself?

**Comment by OKNoah** [comment]
I was able to properly sign the certificate, so no longer an issue for me personally.

**Comment by Findus23** [comment]
Thanks for the report, it wouldn't surprise me if the library didn't accept self-signed certificates.
But I don't think that's a huge issue as a Matomo instance with a invalid cert, won't be able to track properly (apart from intranet setups)
