### ISSUE TITLE
Homepage wrong on NPM

### ISSUE THREAD

**Issue by JeffResc** [matomo-org/matomo-nodejs-tracker#63]
Simple issue, the homepage on NPM links to [matomo-tracker](https://github.com/matomo-org/matomo-tracker) rather than [matomo-nodejs-tracker](https://github.com/matomo-org/matomo-nodejs-tracker) which may confuse some.

**Comment by Findus23** [comment]
Seems like this has been fixed in https://github.com/matomo-org/matomo-nodejs-tracker/pull/58, but I did not do a release since.

I'll see if I can get a release to work.

**Comment by Findus23** [comment]
And it seems to have worked:
https://github.com/matomo-org/matomo-nodejs-tracker/releases/tag/v2.2.2

**Comment by JeffResc** [comment]
Looks good 👍
